---
title: Sense HAT data logger
hero_image: images/banner.png
description: Create a data-logging device using the Sense HAT hardware and Python
original_url: https://raspberrypi.org/learning/sense-hat-data-logger
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: raspberry-pi, python, sense-hat
site_areas: projects
hardware: raspberry-pi, sense-hat
software: python
version: 4.0.1
last_tested: 2017-01-01
steps:
- title: Introduction
- title: Getting data from the Sense HAT
- title: Writing the data to a file
  completion:
  - engaged
- title: Adding a header to the CSV file
  completion:
  - engaged
- title: Recording at specific time intervals
- title: Starting your data logger on boot
<<<<<<< HEAD
- title: 'Challenge: selecting the data to be recorded'
  completion:
  - internal
=======
  completion:
  - internal
- title: 'Challenge: selecting the data to be recorded'
>>>>>>> master
